src/App.tsx
src/utils/useFetchData.ts

Small polishing, nothing fancy

polishing useFetchData

---

package-lock.json
package.json

fix for @mui/icons-material

---

src/components/Header/ActiveLink.tsx
src/components/Header/Header.tsx
src/components/Header/NavMenu.tsx
src/components/Header/Styles.tsx

1. Fixed styles in the `header` component.
2. Implemented the value of theme for components (not everywhere).
3. Removed unnecessary custom components.
4. Fixed the path to `logo.svg`.
[Video](https://www.loom.com/share/562f03fc28914bb5ae34937ab8c0dcdc?sid=a83bb95d-11d9-4c97-a8dd-3fcfecfbfb42)

fix and refactor code header in header component

---

package-lock.json
src/components/ForTesting/Dump.tsx
src/components/ProductCard/ProductCard.tsx
src/context/CartContext/CartContext.tsx
src/main.tsx

The add to cart button now updates the local state of the cart. 
The first click on the button to add an item to cart will add it to the cart.
The second click on the button deletes the item from the local state of the shopping cart.

the add to cart button now updates the local state of the cart

---

src/components/NewModels/NewModels.tsx
src/context/CartContext/CartContext.tsx

Bug with incrase and decrease function has been fixed

---

src/components/ProductCard/ProductCard.tsx
src/context/FavoritesContext/FavoritesContext.tsx
src/context/FavoritesContext/FavoritesContextType.tsx
src/hooks/useFavoritesContext.ts
src/main.tsx

1. added favorites to the local storage
2. added to ProductCard functionality of adding and removing from favorites

[Favorites]

---

src/components/ForTesting/Dump.tsx
src/components/HotPrices/HotPrices.tsx

Hot prices section has been added.

Hot prices section

---

src/components/CategoryPage/CategoryPage.tsx

**DESCRIPTION**
Category Page. Title of category has been fixed
Before:
After:

Title of category has been fixed

---

src/components/ProductCard/ProductCard.tsx

item picture positioning is now independent of text size

item picture positioning is now independent of text size

---

src/components/ProductCard/ProductCard.tsx

Tooltip has been added to productCard name

Tooltip has been added to productCard name

---

src/components/CartModal/CartModal.tsx
src/components/CartModal/index.ts
src/pages/CartPage/CartPage.tsx

Added modal, toasts are in progress

added adaptive modal, validation and so

---

src/components/AboutSection/About.tsx
src/components/AboutSection/index.ts
src/components/Container/Container.tsx
src/components/Container/index.ts
src/pages/ProductPage/ProductPage.styles.tsx
src/pages/ProductPage/ProductPage.tsx
src/pages/ProductPage/index.ts
src/types/ProductExpanded.ts
src/types/index.ts

1. `About Section` has been added on `Product Page`(both mobile and desktop).
2. Code has been formatted in `Product Page` component.
3. `index.ts` files have been added.

About Section has been added on Product page

---

src/components/AboutSection/About.tsx
src/components/AboutSection/index.ts
src/components/Container/Container.tsx
src/components/Container/index.ts
src/pages/ProductPage/ProductPage.styles.tsx
src/pages/ProductPage/ProductPage.tsx
src/pages/ProductPage/index.ts
src/types/ProductExpanded.ts
src/types/index.ts

1. `TechSpecs Section` has been created as `Table`.
2. Desktop and mobile versions have been implemented.

TechSpecs section has been created on Product Page

---

src/components/NewModels/NewModels.tsx

Filter is updated. But since the list of products for 2022 only displays phones (iphone 13 and 14) and the pictures are the same, the display is not very relevant

Fix new models filter

---

src/components/BreadCrumbs/BreadCrumbsComponent.tsx
src/pages/CartPage/CartPage.tsx
src/pages/CategoryPage/CategoryPage.tsx
src/pages/FavoritesPage/FavoritesPage.tsx
src/pages/ProductPage/ProductPage.tsx

Breadcrumbs has been added

---

src/components/RecommendedProducts/Recommended.tsx
src/components/RecommendedProducts/index.ts
src/pages/ProductPage/ProductPage.styles.tsx
src/pages/ProductPage/ProductPage.tsx

New component on product page - recommended
Filtered by name and color, sorted by price

added recommended component

---

src/components/BurgerMenu/BurgerActiveLink.tsx
src/components/Header/ActiveLink.tsx
src/components/Header/Header.styles.tsx
src/components/Header/Header.tsx
src/components/Header/NavBarButtons.tsx
src/components/Header/NavMenu.tsx

1. Hover effect has been added to Header links.
2. Active Effect has been added to BurgerMenu links.
3. Code refactored and fixed.

Code has been refactored and added hover animation

---

src/components/BreadCrumbs/BreadCrumbsComponent.style.tsx
src/components/BreadCrumbs/BreadCrumbsComponent.tsx
src/components/BreadCrumbs/index.ts

1. Hover effect has been added to links (`scale: 1.05`).

hover effect has been added to links

---

src/pages/CategoryPage/CategoryPage.tsx

when the list is empty it shows this message `There are no phones/tablets/accessories/products matching the query`

Category page updated

---

src/components/Header/Search.tsx

- debounce fixed
- path fixed
- input focus added

Fix search

---

src/pages/CategoryPage/CategoryPage.tsx

Pagination has been fixed

---

src/pages/CategoryPage/CategoryPage.tsx

Pagination fixes

---

src/components/ImageSelector/ImageSelector.tsx

https://github.com/fs-jan24-midnight-coup/react_phone-catalog/assets/66799002/7be27f3c-713f-4e4f-8ba4-227e41ffa2d1

fixed, now works properly

---

src/components/ProductSliderFabric/ProductSliderFabric.tsx
src/pages/HomePage/HomePage.tsx
src/types/FilterCallback.ts

Fabric for grid containers has been created

Fabric for grid containers has been created

---

src/pages/NotFoundPage/NotFoundPage.tsx

Not found page has been changed

Not found page has been changed

---

package-lock.json
package.json
src/pages/NotFoundPage/NotFoundPage.tsx

Animated pic has been added to the not found page

Animated pic has been added to the not found page

---

src/pages/CategoryPage/CategoryPage.tsx

transitions in category have been added

transitions in category

---

package-lock.json
package.json
src/pages/CartPage/CartPage.tsx
src/pages/CategoryPage/CategoryPage.tsx
src/pages/NotFoundPage/NotFoundPage.tsx

Design of empty cart

---

src/pages/CartPage/CartPage.tsx
src/pages/FavoritesPage/FavoritesPage.tsx

Design of favorites page with empty state

Design of favorites page with empty state

---

src/components/BurgerMenu/BurgerMenu.styles.tsx
src/components/Header/Header.styles.tsx
src/components/Header/Search.tsx
vite.config.ts

##DESCRIPTION 
1. Styles have been fixed in header.
2. New icon has been added for hiding search field.
3. New button for clearing field has been added.

bugfix-styles-in-header

---

src/App.tsx
src/Root.tsx
src/components/BurgerMenu/BurgerActiveLink.tsx
src/components/BurgerMenu/BurgerMenu.tsx
src/components/BurgerMenu/BurgerMenuButtons.tsx
src/components/Header/ActiveLink.tsx
src/components/Header/Header.tsx
src/components/Header/NavBarButtons.tsx
src/components/Header/Search.tsx
src/components/Overlay/Overlay.style.tsx
src/components/Overlay/index.ts
src/components/index.ts
src/context/BurgerMenuContext/BurgerMenu.types.ts
src/context/BurgerMenuContext/BurgerMenuContext.tsx
src/context/BurgerMenuContext/index.ts
src/context/SearchContext/SearchContext.tsx
src/context/SearchContext/SearchContext.types.ts
src/context/SearchContext/index.ts
src/hooks/useBurgerMenuContext.ts
src/hooks/useSearchContext.ts
src/main.tsx

1. Context for `Search` has been added.
2. Context for `BurgerMenu` has been added.
3. `Overlay` component has been added.
4. Bug with URL has been fixed(now after click on `burger` button URL will set to default and will close `search` field)

fixes-and-refactor-in-header-and-burgermenu

---

src/components/ProductSliderFabric/ProductSliderFabric.tsx

Product slider has been fixed

---

src/pages/ProductPage/ProductPage.styles.tsx

Fixed center image gallery and block with button on adaptive

Fixed center image gallery on adaptive

---

src/pages/CategoryPage/CategoryPage.tsx

Pagination on the small screen has been fixed
Before:
After:

Pagination on the small screen has been fixed

---

src/pages/ProductPage/ProductPage.styles.tsx

Fixed info block product card on adaptive

Fixed info block product card on adaptive

---

src/pages/CategoryPage/CategoryPage.tsx

pagination additional fix
